#**PROJECT TITLE**
"Bank Marketing Campaign Analysis & Term Deposit Prediction”

# **Objective(Problem statment)**

1. To analyze customer demographics and financial characteristics to understand the profile of customers targeted by the bank.
2. To evaluate the effectiveness of marketing campaigns based on factors such as contact method, month, campaign duration, and number of contacts.
3. To identify the key factors influencing term-deposit subscriptions and determine which customer characteristics are associated with higher conversion rates.
4. To segment customers based on their characteristics and campaign responses to identify high-potential customer groups.
5. To develop a predictive model that can identify customers who are more likely to subscribe to a term deposit, helping the bank improve its marketing strategy

# Outcome

The project can focus on Predicting whether a bank customer will subscribe to a term deposit based on their demographic, financial, and campaign-related characteristics.

# Domain
Banking campaign analysis

#**Dataset Information**

**Source:** UCI ML Repository  <font color="blue"><u> **https://archive.ics.uci.uci.edu/dataset/222/bank+marketing**</font></u>

**Year / Timeline:** Data collected during 2014 to 2019

**Dataset Column/features Description:**

*   **Age** -Customer Age
*   **job** - Type of occupation/job (Categorical)
*   **marital** - Marital status of the customer (Categorical)
*   **education** - Education level (Categorical)
*   **default** - Whether the customer has credit in default (Categorical)
*   **balance** - Average yearly balance in the customer's bank account (Numerical)
*   **housing** - Whether the customer has a housing loan (Categorical)
*   **loan** - Whether the customer has a personal loan (Categorical)
*   **contact** - Communication method used to contact the customer (Categorical)
*   **day** - Day of the month when the customer was last contacted (Numerical)
*   **month** - Month when the customer was last contacted (Categorical)
*   **duration** - Duration of the last contact, in seconds (Numerical)
*   **campaign** - Number of contacts made during the current campaign (Numerical)
*   **pdays** - Number of days since the customer was last contacted in a previous campaign (Numerical)
*   **previous** - Number of contacts made before the current campaign (Numerical)
*   **poutcome** - Outcome of the previous marketing campaign (Categorical)
*   **y** - Whether the customer subscribed to a term deposit (yes/no)

# Stages for DA Project

## Stage 1 – Problem Definition and Dataset Selection



1. *Business problem:*
Identify the customer characteristics and campaign factors that influence term-deposit subscriptions and use the available data to understand which customers are more likely to subscribe.
2. *Expected Outcome:*
Analyze customer and campaign data to identify patterns associated with term-deposit subscriptions and develop insights that can help the bank improve the effectiveness of its marketing campaigns.

# **Inital EDA**

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# 1) Load the Dataset
url = "https://raw.githubusercontent.com/Keerthanadevi-R15/-Bank-Marketing-Campaign-Analysis-Term-Deposit-Prediction-/main/raw%20dataset%20for%20bank.csv"
df = pd.read_csv(url, sep=';')

In [ ]:
df.head()

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
0,58,management,married,tertiary,no,2143,yes,no,unknown,5,may,261,1,-1,0,unknown,no
1,44,technician,single,secondary,no,29,yes,no,unknown,5,may,151,1,-1,0,unknown,no
2,33,entrepreneur,married,secondary,no,2,yes,yes,unknown,5,may,76,1,-1,0,unknown,no
3,47,blue-collar,married,unknown,no,1506,yes,no,unknown,5,may,92,1,-1,0,unknown,no
4,33,unknown,single,unknown,no,1,no,no,unknown,5,may,198,1,-1,0,unknown,no

In [ ]:
# dataset shape

df.shape

(45211, 17)

In [ ]:
# Dataset information

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45211 entries, 0 to 45210
Data columns (total 17 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   age        45211 non-null  int64
 1   job        45211 non-null  object
 2   marital    45211 non-null  object
 3   education  45211 non-null  object
 4   default    45211 non-null  object
 5   balance    45211 non-null  int64
 6   housing    45211 non-null  object
 7   loan       45211 non-null  object
 8   contact    45211 non-null  object
 9   day        45211 non-null  int64
 10  month      45211 non-null  object
 11  duration   45211 non-null  int64
 12  campaign   45211 non-null  int64
 13  pdays      45211 non-null  int64
 14  previous   45211 non-null  int64
 15  poutcome   45211 non-null  object
 16  y          45211 non-null  object
dtypes: int64(7), object(10)
memory usage: 5.9+ MB

In [ ]:
# Column Names

df.columns

Index(['age', 'job', 'marital', 'education', 'default', 'balance', 'housing',
       'loan', 'contact', 'day', 'month', 'duration', 'campaign', 'pdays',
       'previous', 'poutcome', 'y'],
      dtype='object')

In [ ]:
#Statistical Summary

df.describe()

,age,balance,day,duration,campaign,pdays,previous
count,45211.000000,45211.000000,45211.000000,45211.000000,45211.000000,45211.000000,45211.000000
mean,40.936210,1362.272058,15.806419,258.163080,2.763841,40.197828,0.580323
std,10.618762,3044.765829,8.322476,257.527812,3.098021,100.128746,2.303441
min,18.000000,-8019.000000,1.000000,0.000000,1.000000,-1.000000,0.000000
25%,33.000000,72.000000,8.000000,103.000000,1.000000,-1.000000,0.000000
50%,39.000000,448.000000,16.000000,180.000000,2.000000,-1.000000,0.000000
75%,48.000000,1428.000000,21.000000,319.000000,3.000000,-1.000000,0.000000
max,95.000000,102127.000000,31.000000,4918.000000,63.000000,871.000000,275.000000

## Stage 2 – Data Cleaning and Pre-processing

In [ ]:
# Check Missing Values

df.isnull().sum()

age          0
job          0
marital      0
education    0
default      0
balance      0
housing      0
loan         0
contact      0
day          0
month        0
duration     0
campaign     0
pdays        0
previous     0
poutcome     0
y            0
dtype: int64

In [ ]:
# Duplicate Record Check

df.duplicated().sum()

np.int64(0)